### ISSUE TITLE
Testing Phase - Part 1 (Vibhu)

### ISSUE THREAD

**Issue by supaboi21** [SleepWorkers/Project-SIGHT#14]
**Task priority**: HIGH

# Task description
Testing components (non-TI) till the TI components get delivered. Get the basic framework ready, the system diagram is needed.

**Person assigned**: @supaboi21 
**Deadline**: Till TI components get delivered or _1<sup>st</sup> Februrary 2019_
**Branch name**: supaboi21

**Pending Non-TI items to buy**
- [x] MPU 9250 or another appropriate IMU with 9+ DoF
- [x] Flex sensor 4.5" length for longer sensors

## Things that need to be done before parts arrive
- [ ] Algorithm for flex sensor for all five fingers
    - [ ] 2.2" for thumb and 4.5" for others
- [ ] Algorithm for IMU
- [ ] Algorithm for pulse sensor

# Must Haves
 - [ ] System Diagram
    - [ ] Connection between parts for the prototype stage (with arduino mega)
- [ ] Algorithm for pose estimation of the fingers
    - [ ] Pose of thumb with respect to palm (2.2" flex sensor)
    - [ ] Pose of other fingers with respect to palm (4.5" flex sensor)
        - [ ] Index
        - [ ] Middle
        - [ ] Ring
        - [ ] Little
- [ ] IMU working and transformations 
    - [ ] IMU + transformation to finger joints
- [ ] Get BPM

## Extras
- [ ] API if there is time
