### ISSUE TITLE
Main task list for @TheProjectsGuy

### ISSUE THREAD

**Issue by TheProjectsGuy** [SleepWorkers/Project-SIGHT#15]
**Task priority**: HIGH

# Task description
Given the flex sensors, figure out an algorithm for finding joint angles from the stress values of the flex sensor. Pointwise needs are as follows:
- Making a full-fledged API for the Flex Sensor

**Person assigned**: [@TheProjectsGuy](https://github.com/TheProjectsGuy)

**Deadline**: Tuesday, 19<sup>th</sup> March 2019 (Final submission)

# Procedural steps
## Step 1: Simulation
Get a simulation up and running, giving useful values as proof of concept. 
- [x] MATLAB Simulink Simulation
    - [x] Find the correct values of variables to be used
- [x] Import to other versions and documentation
- [x] Shift changes to `dev` branch through a _pull request_

### Electrical circuitry 
- [x] Make a CAD file with reference to the simulation circuit (preferably in eagle)
- [x] Build up the circuitry on a breadboard
- [x] Test with Arduino Mega

### Computer vision part
We'll use LEDs to find angles. Use CV to get joint angles while simultaneously recording the flex sensor readings
- [x] Make a CAD file for the LED connections (voltage divider circuitry)
- [x] OpenCV Algorithm
    - [x] Hunt for the best algorithm that fits the purpose
    - [x] Test algorithm with LEDs arranged in a fashion through a laptop webcam
    - [x] Test on a web camera 
- [x] Python script
    - [x] Arduino (Reading the flex sensor values)
    - [x] OpenCV code
    - [ ] ~~Implement both in a class-wise fashion and use synchronized multithreading to handle both, see if output comes on console~~

## Step 4: Algorithm
- [x] Data collection
    - [x] Store everything in a numpy database for training algorithm
- [ ] Figure out an algorithm for converting the stress values into joint angles

## Step 4: Frame visualization 
- [ ] Visualize frames on a visualization platform 

# Extras
**Priority**: LOW
Here are some extra things that can be implemented, if time permits:
- [ ] Implementation in C++ (C++ API)
- [ ] Phone side application for 
    - [ ] iOS
    - [ ] Android
- [ ] Computer side application for 
    - [ ] Ubuntu
    - [ ] MacOS

**Comment by TheProjectsGuy** [comment]
⚠️ Scrap this comment ⚠️ 
# Step 1
Simulation done, file in `Flex_Sensor_final_circuitry.slx` (folder [here](https://github.com/SleepWorkers/Project-SIGHT/tree/dev/test/avneesh_test_phase1/MATLAB_tests/Simulink), more [here](https://github.com/SleepWorkers/Project-SIGHT/tree/dev/test/avneesh_test_phase1/MATLAB_tests))
## Materials required 
- [x] Flex sensor 2.2''
- [ ] Resistors
    - For instrumentation amplifier
        - [ ] 1.5 kΩ resistors (x 2)
        - [ ] 180 Ω resistors (x 2)
        - [ ] 22 kΩ resistors (x 2)
    - For the wheatstone bridge
        - [ ] 80 kΩ resistors (x 2) for the upper arms
        - [ ] 70 kΩ resistor (x 1) for the reference arm (lower resistor) 
- [x] Op-Amps (x 3) for the instrumentation amplifier construction
- [ ] Breadboard and jumper wires
- [ ] Arduino and multimeter for programming and debugging

## Post planned progress 
CAD starts tomorrow
