### ISSUE TITLE
Simulation of Flex sensor circuitry

### ISSUE THREAD

**Issue by TheProjectsGuy** [SleepWorkers/Project-SIGHT#16]
**Task priority**: HIGH

# Task description
Simulation of Flex sensor circuitry on MATLAB.
References issue #15 (Main task list for @TheProjectsGuy)

**Person assigned**: [@TheProjectsGuy](https://github.com/TheProjectsGuy)

**Deadline**: Sunday, 5<sup>th</sup> February 2019

# Must Haves
Get a simulation up and running, giving useful values as proof of concept. 
- [x] MATLAB Simulink Simulation
    - [x] Find the correct values of variables to be used
- [x] Import to other versions (R2016a) and documentation 
- [x] Shift changes to `dev` branch through a _pull request_

## Extras
Things that could be worked on after the _must haves_ are finished.
- [x] Interactive mode to change all the values and see things easily

Attach all results to this issue as well, for documentation purposes

**Comment by TheProjectsGuy** [comment]
Tests done on the **2.2'' flex sensor**
### Reasons for failure
1. Unavailability of exact resistance values
## ~~MATLAB Trial 1~~ !! Test Failed !! :warning: 
Edited the default configurations for the flex sensor and stored in the file `Flex_Sensor_final_circuitry.slx`. The default values for resistors was decided to be 1.5 kΩ + 180 Ω for input and 22 kΩ for feedback. The results are as follows:
- Circuit design in simulation
    ![screenshot from 2019-02-01 22-50-30](https://user-images.githubusercontent.com/29420733/52138663-d9e0e580-2673-11e9-885b-e12f7535579d.png)
- The output designs are as follows
    ![screenshot from 2019-02-01 22-49-48](https://user-images.githubusercontent.com/29420733/52138707-f3822d00-2673-11e9-8df4-d2b81d9632c4.png)
        - *Vout*: Output voltage of instrumentation amplifier: 0.459 V to 4.97 V (difference of **4.51 V**)
        - *Raw output*: Output of voltage divider (wheatstone bridge): 0.0351 V to 0.38 V (difference of **0.345 V**)
        - Amplification factor = 13.095

## ~~Parts needed~~ :warning: :name_badge: 
### Circuitry
- [ ] Flex sensor 2.2''
- [ ] Resistors
    - For instrumentation amplifier
        - [ ] 1.5 kΩ resistors (x 2)
        - [ ] 180 Ω resistors (x 2)
        - [ ] 22 kΩ resistors (x 2)
    - For the wheatstone bridge
        - [ ] 80 kΩ resistors (x 2) for the upper arms
        - [ ] 70 kΩ resistor (x 1) for the reference arm (lower resistor) 
- [ ] Op-Amps (x 3) for the instrumentation amplifier construction
- [ ] Breadboard and jumper wires
- [ ] Arduino and multimeter for programming and debugging

**Comment by TheProjectsGuy** [comment]
Simulation solved

**Comment by TheProjectsGuy** [comment]
The resistance values will have to be tweaked because of limited availability, the available resistors are as shown below
![Resistance values available](https://5.imimg.com/data5/FC/AW/MY-14308383/resistor_box_500-500x500.jpg)
Suggested to make modifications ASAP, deadline shifted to Tuesday, 5<sup>th</sup> February 2019...

**Comment by TheProjectsGuy** [comment]
Tests done on the **2.2'' flex sensor**
## ~~MATLAB Trial 2~~ :warning: TEST FAILED
Edited the default configurations for the flex sensor and stored in the file `FlexSensor_Customizable_2in2.slx`. The default values for resistors was decided to be:
- 100 kΩ for upper arm and 68 kΩ for lower arm at the **wheatstone bridge**.
- 8.2 kΩ for input and 100 kΩ for feedback, giving a gain of 12.195 at the **instrumentation amplifier**. 

The results are as follows:
- Circuit design in simulation
    ![flexsensor_2in2_custom](https://user-images.githubusercontent.com/29420733/52245907-88ea1f00-2909-11e9-8dbd-544322fbb9b9.png)
- The output designs are as follows
    - *Vout*: Output voltage of instrumentation amplifier: 5.03 V to 0.844 V (difference of **4.18 V**)
    - *Raw output*: Output of voltage divider (wheatstone bridge): 0.0692 V to 0.4121 V (difference of **0.3429 V**)

## ~~Parts needed~~ :warning: 
### Circuitry
:warning: :warning: Issue outdated, please skip this list :warning: :warning: 
- [ ] Flex sensor 2.2''
- [ ] Resistors
    - For instrumentation amplifier
        - [ ] 8.2 kΩ resistors (x 2)
        - [ ] 100 kΩ resistors (x 2)
    - For the wheatstone bridge
        - [ ] 100 kΩ resistors (x 2) for the upper arms
        - [ ] 68 kΩ resistor (x 1) for the reference arm (lower resistor) 
- [ ] Op-Amps (x 3) for the instrumentation amplifier construction
- [ ] Breadboard and jumper wires
- [ ] Arduino and multimeter for programming and debugging
- [ ] 2 Position [Male FCI connectors](https://www.tanotis.com/products/sparkfun-amphenol-fci-clincher-connector-2-position-male?variant=42402341200)

**Comment by TheProjectsGuy** [comment]
## Flex Sensor testing
| **Flex Sensor length** | **Finger**(s) | **Resistance at full inward bend** | **Resistance at full outward flex** | **Comments** |
| :----: | :----: | ---- | ---- | ---- |
| `2.2in` | Thumb | 75 kΩ | 130 kΩ | Flex sensor has to be used with translucent side facing outwards, hence values are reversed. Suggested to change the position on wheatstone bridge |
| `4.5in` | All four 3 joint fingers | 25 kΩ | 8.5 kΩ | Flex sensor has to be used with black line facing inwards. Suggested to maintain the position on the wheatstone bridge |

Since the flex sensor readings are different, the resistance values will **have** to be tweaked along with a factor of safety (to avoid _out of bounds cases_). It's suggested to use:
- 1 kΩ factor of safety for `4.5in` flex sensors
- 2 kΩ factor of safety for `2.2in` flex sensors

Thus, the ranges are:
- `2.2in`: 73 kΩ to 132 kΩ.
- `4.5in`: 26 kΩ to 7.5 kΩ

## Course of action
- [x] Abondon **version 1**
    - Test results: :warning: Test failed :warning: 
    - Test output
        - Make versatile circuitry
- [x] Start **Version 2**

These will keep everything in bound... Task list:
- [x] Voltage divider network for both the flex sensor types
- [x] Determine the constant reference voltage arm to be used for the wheatstone bridge
- [x] New resistance values to be found
- [x] Documentation update

**Comment by TheProjectsGuy** [comment]
Remaining task list:
## CAD Files
Using Eagle, create the following CAD files
- [x] CAD for 2.2" flex sensor
- [x] CAD for 4.5" flex sensor
- [x] CAD for entire hand using the analog MUX
- [x] Bill of materials - BOM

**Comment by TheProjectsGuy** [comment]
Issue solved on Saturday, 16<sup>th</sup> February 2019. Proceeding to the next issue in hand
