### ISSUE TITLE
IMU Configuration for Pose Estimation

### ISSUE THREAD

**Issue by supaboi21** [SleepWorkers/Project-SIGHT#18]
**Task priority**: HIGH

# Task description
Write Algorithm for IMU [LSM9DS1](https://www.sparkfun.com/products/13284) \(Pose Estimation\) 

**Person assigned**: [@supaboi21](https://github.com/supaboi21)

**Deadline**: 13<sup>th</sup> February 2019

# Procedure (Step by Step)
### Deadline: 6<sup>th</sup> February 2019
- [ ] LSM9DS1
    - [ ] Connections (Arduino | MSP430)
- [ ] MSP430FR2355

### Deadline: 12<sup>th</sup> February 2019
- [ ] Paper/Code Hunting 
- [ ] Implementation

### Deadline: 13<sup>th</sup> February 2019
- [ ] Debugging
# Must Haves
- [ ] Output neccessary output over which Gesture Recognition will work

## Extras
- [ ] Integration with #15 for Gesture Recognition

**Comment by supaboi21** [comment]
This Issue is Modified and will be ccarried on there.
