### ISSUE TITLE
Subgoals for @TheProjectsGuy

### ISSUE THREAD

**Issue by TheProjectsGuy** [SleepWorkers/Project-SIGHT#21]
**Task priority**: HIGH

# Task description
The interim submission deadline is approaching and you need to finish the tasks under _Must Haves_. It is also suggested that you finish the tasks under _Extras_.
This issue spawns from #15 

**Person assigned**: Task assigned to @TheProjectsGuy 

**Deadline**: Thursday, 21<sup>st</sup> March 2019

# Must Haves
## Before getting started
Here are the things that you have to do:
- [x] Review and test everything that you've on the `dev` branch, do the following:
    - [x] Individual tests.
    - [x] Move everything that's working into appropriate folders and everything that's not working into the `Project-SIGHT/test/contrib/avneesh_tests_v1/` folder.
    - [x] Documentation work
    - [x] Merge into `master` with a _pull request_.
- [x] Create a branch `avneesh-dev-1` for the development process (from the dev branch). Everything happens in the `test` folder.
Actual process starts from hereon...
:warning: Everything handled in folder `avneesh_test_files` on branch `avneesh-test-pahse1` :warning: 

## Algorithm
- [x] Develop code to read analog readings from the flex sensor
    - Make code as generic as possible, because of ADCs having different precision
    - Can be on Arduino as well
- [ ] Using OpenCV, make an algorithm to find angles 
    - You'll use it for joint angles
    - [x] CAD for LED circuitry
    - [ ] Procure a webcam
- [ ] Python script to collect training examples
    - Synchronous multithreading: for the CV and ADC readings over serial
- [ ] Collect training examples for the training, cross validation and test set
    - [ ] Create a dataset with joint angles as output and stress voltage as input
- [ ] Train algorithm
- [ ] Final test of the algorithm, without the CV verification part
    - Test for consistency and reliability
- [ ] Port the weights and model architecture into code for microcontroller(s)
    - Arduino and TI CCS (or Energia)

## Flex Sensors
All this on breadboard
- [x] Final code to interface flex sensors to Arduino using analog mux
- [x] Final code to interface flex sensors to TI SimpleLink CC3220SF WiFi MCU
    - [x] TI SimpleLink CC3220SF WiFi MCU quick start. All codes in folder named `test/ti_cc3220sf/`.
        - [x] Digital I/O
        - [x] Timers, delays, etc.
        - [x] ADCs
        - [x] Serial communication
    - [x] Single Flex sensor (without the analog mux) code
    - [x] Multiple Flex sensor code (using the analog mux)
    - Everything should be visible on a terminal

All this on a veroboard (port from breadboard)
- [ ] Eagle board design 
- [ ] Solder the board 
    - [ ] Procure components
- [ ] Final test

## Extras
Things that could be worked on after the _must haves_ are finished.
- [ ] Python script to get values from terminal and display them onto a GUI like RViZ
    - This could be a good start to ROS API (but it's a long shot)
- [ ] Integration with various other frames
    - Native DH parameter API for first level developers

# References
- TI SimpleLink CC3220SF 
    - [website](http://www.ti.com/tool/CC3220SF-LAUNCHXL)
    - datasheets in your drive
- OpenCV [documentation](https://docs.opencv.org)

**Comment by TheProjectsGuy** [comment]
All CV based progress can be tracked under issue #22 or on branch `avneesh-test-cv`

**Comment by TheProjectsGuy** [comment]
Chose the following for development:
    - [Energia](energia.nu/)
    - [CCS](http://www.ti.com/tool/CCSTUDIO)
    - [dev.ti.com](https://dev.ti.com/)

**Comment by TheProjectsGuy** [comment]
Everything ported to trello
