### ISSUE TITLE
Algorithm to determine joint angles

### ISSUE THREAD

**Issue by TheProjectsGuy** [SleepWorkers/Project-SIGHT#22]
**Task priority**: HIGH

# Task description
Design and implement an algorithm to measure angles using CV. You're given a chain of LEDs and you have to estimate the angle subtended at every LED in between. This will be used for the CV based training tool. You're free to decide how to store the data collected. This issue is a direct sub issue of #21 

**Person assigned**: @TheProjectsGuy 

**Deadline**: Saturday, 23<sup>rd</sup> February 2019

# Must Haves
## Before getting started
- [x] Create a branch `avneesh-test-cv` from `dev` and do all work in a folder named `Project-SIGHT/test/avneesh_test_files/cv_algo`

### CAD
Your circuitry requires
- [x] Eagle CAD file for connections and layouts

### Arduino code
- [x] Code for Arduino

### Python code
Your Python code for detection must do the following
- [x] Get an image from a source containing 
    - The image will have green LEDs. The chain order can be decided based upon their intensities. 
- [ ] Create a mask for every intensity threshold
    - Localized histogram analysis can be used
    - The three joint fingers will have 5 chain LEDs and two joint fingers will have 4 chain LEDs
    - The ultimate result must be able to indicate the index of every member of chain
- [ ] Connect them using lines in a GUI window
- [ ] Find angles for every member of chain
    - Except the first and last member (because there are no angles subtended there)
- [x] Store the recorded angles in a numpy based `.npy` file

## Extras
- [ ] Synchronized multithreading (for now generate a random number in synchronous and store that too in the file

**Comment by TheProjectsGuy** [comment]
The LED approach will fail at this stage since all LEDs give nearly the same brightness factor. Will have to go with hand labelling dataset. Will need to buy a few items as discussed on Slack group. We will need more resistor ranges, according to the MATLAB script.

**Comment by TheProjectsGuy** [comment]
# Test 1
The effectiveness of the circuit that we build with the resistors we have is very less and the current in the sidearm of the Wheatstone bridge will be too high for the microcontroller. Results are from 
**Results**
![screenshot from 2019-02-24 10-03-41](https://user-images.githubusercontent.com/29420733/53295371-e80fc500-381f-11e9-8126-ac4767609b8d.png)
![screenshot from 2019-02-24 10-04-14](https://user-images.githubusercontent.com/29420733/53295377-11c8ec00-3820-11e9-9d40-c6f616fb6512.png)
**Ideal** desired output
![screenshot from 2019-02-24 10-01-00](https://user-images.githubusercontent.com/29420733/53295381-23aa8f00-3820-11e9-8f30-4e45e9b63c5e.png)
![screenshot from 2019-02-24 10-05-36](https://user-images.githubusercontent.com/29420733/53295382-273e1600-3820-11e9-8bd8-3dab992a0c66.png)

Suggested to buy the resistors pack

Needed the following:
- FCI 2 terminal connectors for flex sensors (3 will also work)
- Jumper wires for connecting LEDs more efficiently

**Comment by TheProjectsGuy** [comment]
No image processing technique found useful, issue scrapped
