### ISSUE TITLE
Phase 1 - Interim - TheProjectsGuy

### ISSUE THREAD

**Issue by TheProjectsGuy** [SleepWorkers/Project-SIGHT#29]
**Task priority**: HIGH

# Task description
Getting to know your board `TI SimpleLink WiFi CC3220SF MCU`. You must learn all the basic driver features of your board and then proceed to phase 2 of the project. Spawns from issue #21 

**Person assigned**: @TheProjectsGuy 

**Deadline**: Sunday, 3<sup>rd</sup> March 2019

# Must Haves
Learn the following:
- [x] GPIO 
    - [x] Writing values
    - [x] Reading values
    - [x] Interrupts
- [x] PWM Generated output (Analog Output)
- [x] Analog Input through ADCs
- [x] Basic communication protocols
    - [x] Serial
    - [ ] I2C
    - [x] SPI

## Extras
Things that could be worked on after the _must haves_ are finished.
- [ ] WiFi SDK readthrough

**Comment by TheProjectsGuy** [comment]
Work happening on `avneesh-test-phase1` [branch](https://github.com/SleepWorkers/Project-SIGHT/tree/avneesh-test-phase1).
