### ISSUE TITLE
Create CV Data creation bridge

### ISSUE THREAD

**Issue by TheProjectsGuy** [SleepWorkers/Project-SIGHT#33]
**Task priority**: HIGH

# Task description
Create a data creation tool for the `flex sensor circuitry reading` Vs `joint angle` dataset. Direct sub-issue of #15.

**Person assigned**: @TheProjectsGuy 

**Deadline**: Sunday, 10<sup>th</sup> March 2019

# Must Haves
- [x] TI Board code
    - That will read from ADC based on a command received and send result
- Python end code
    - [x] Serial parser
    - [x] Snap image and save serial readings in a `.npy` file
    - [x] Convert image to joint angles using selection tool. Then save joint angles Vs serial readings in a `.npy` file
        - This is the dataset

## Extras
Things that could be worked on after the _must haves_ are finished.
- Check out the algorithms for training 
    - Neural Networks
    - Perceptron

**Comment by TheProjectsGuy** [comment]
Everything done in `v1` folder of `cv_bridge`

**Comment by TheProjectsGuy** [comment]
Code ready on `avneesh-dev-1` [branch](https://github.com/SleepWorkers/Project-SIGHT/tree/avneesh-dev-1). The solution is present in the [cv_bridge](https://github.com/SleepWorkers/Project-SIGHT/tree/avneesh-dev-1/test/avneesh_test_files/cv_bridge) folder.
